"""add note for inv, total for item

Revision ID: 3b9b23e64a7b
Revises: 29b6db45af9a
Create Date: 2025-12-28 14:09:36.634709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b9b23e64a7b'
down_revision: Union[str, Sequence[str], None] = '29b6db45af9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice', sa.Column('note', sa.String(), nullable=True))
    op.add_column('invoice_item', sa.Column('total', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice_item', 'total')
    op.drop_column('invoice', 'note')
    # ### end Alembic commands ###
