"""pgvector

Revision ID: 60eb7e3604b9
Revises: 3b9b23e64a7b
Create Date: 2025-12-28 17:05:54.804194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# at the top of your migration file
import pgvector.sqlalchemy
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '60eb7e3604b9'
down_revision: Union[str, Sequence[str], None] = '3b9b23e64a7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice_embedding',
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_type', sa.String(), nullable=True),
    sa.Column('items_chunk', sa.String(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_embedding_id'), 'invoice_embedding', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoice_embedding_id'), table_name='invoice_embedding')
    op.drop_table('invoice_embedding')
    # ### end Alembic commands ###
