"""index

Revision ID: 9fcef4e8b908
Revises: c5a128d30c5e
Create Date: 2026-01-01 10:49:44.299284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9fcef4e8b908'
down_revision: Union[str, Sequence[str], None] = 'c5a128d30c5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('mdate', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('groups', 'date')
    op.create_index('idx_reports_account_id', 'reports', ['account_id'], unique=False)
    op.create_index('idx_reports_company', 'reports', ['company'], unique=False)
    op.create_index('idx_reports_deal_stage', 'reports', ['deal_stage'], unique=False)
    op.create_index('idx_reports_first_name', 'reports', ['first_name'], unique=False)
    op.create_index('idx_reports_last_name', 'reports', ['last_name'], unique=False)
    op.create_index('idx_reports_lead_owner', 'reports', ['lead_owner'], unique=False)
    op.create_index('idx_reports_mdate', 'reports', ['mdate'], unique=False)
    op.create_index('idx_reports_source', 'reports', ['source'], unique=False)
    op.add_column('users', sa.Column('mdate', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('users', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('users', 'mdate')
    op.add_column('reports', sa.Column('date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_index('idx_reports_source', table_name='reports')
    op.drop_index('idx_reports_mdate', table_name='reports')
    op.drop_index('idx_reports_lead_owner', table_name='reports')
    op.drop_index('idx_reports_last_name', table_name='reports')
    op.drop_index('idx_reports_first_name', table_name='reports')
    op.drop_index('idx_reports_deal_stage', table_name='reports')
    op.drop_index('idx_reports_company', table_name='reports')
    op.drop_index('idx_reports_account_id', table_name='reports')
    op.drop_column('reports', 'mdate')
    op.add_column('groups', sa.Column('date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('groups', 'mdate')
    op.create_table('haystack_documents',
    sa.Column('id', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('blob_data', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('blob_meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('blob_mime_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('haystack_documents_pkey'))
    )
    op.create_index(op.f('haystack_keyword_index'), 'haystack_documents', [sa.literal_column("to_tsvector('english'::regconfig, content)")], unique=False, postgresql_using='gin')
    op.create_index(op.f('haystack_hnsw_index'), 'haystack_documents', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    # ### end Alembic commands ###
