"""pgvector

Revision ID: cc32668bc370
Revises: 60eb7e3604b9
Create Date: 2025-12-28 17:15:16.143218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = 'cc32668bc370'
down_revision: Union[str, Sequence[str], None] = '60eb7e3604b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_embedding', sa.Column('items_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True))
    op.add_column('invoice_embedding', sa.Column('overall_chunk', sa.Text(), nullable=True))
    op.add_column('invoice_embedding', sa.Column('overall_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True))
    op.alter_column('invoice_embedding', 'items_chunk',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_column('invoice_embedding', 'embedding')
    op.drop_column('invoice_embedding', 'chunk_index')
    op.drop_column('invoice_embedding', 'chunk_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_embedding', sa.Column('chunk_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('invoice_embedding', sa.Column('chunk_index', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('invoice_embedding', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), autoincrement=False, nullable=False))
    op.alter_column('invoice_embedding', 'items_chunk',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('invoice_embedding', 'overall_embedding')
    op.drop_column('invoice_embedding', 'overall_chunk')
    op.drop_column('invoice_embedding', 'items_embedding')
    # ### end Alembic commands ###
