"""create tables

Revision ID: d5a04d4e8d43
Revises: 3f8ca83b8c55
Create Date: 2025-12-28 11:50:41.682439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5a04d4e8d43'
down_revision: Union[str, Sequence[str], None] = '3f8ca83b8c55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('group_name', sa.String(), nullable=False))
    op.drop_column('group', 'name')
    op.add_column('user', sa.Column('user_name', sa.String(), nullable=False))
    op.drop_column('user', 'email')
    op.drop_column('user', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('user', 'user_name')
    op.add_column('group', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('group', 'group_name')
    # ### end Alembic commands ###
