"""reports

Revision ID: e986db83be2c
Revises: 30d56f7c55f0
Create Date: 2025-12-31 12:53:53.541567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = 'e986db83be2c'
down_revision: Union[str, Sequence[str], None] = '30d56f7c55f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('lead_owner', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('deal_stage', sa.String(length=100), nullable=True),
    sa.Column('account_id', sa.String(length=32), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('memo', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.add_column('groups', sa.Column('group_name', sa.String(), nullable=False))
    op.add_column('groups', sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_index(op.f('ix_groups_active'), table_name='groups', postgresql_where='(is_deleted = false)')
    op.create_index(op.f('ix_groups_id'), 'groups', ['id'], unique=False)
    op.drop_column('groups', 'name')
    op.add_column('users', sa.Column('user_name', sa.String(), nullable=False))
    op.add_column('users', sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_index(op.f('ix_users_active'), table_name='users', postgresql_where='(is_deleted = false)')
    op.drop_index(op.f('ix_users_group_id'), table_name='users')
    op.drop_constraint(op.f('uq_users_email'), 'users', type_='unique')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_column('users', 'name')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'])
    op.create_index(op.f('ix_users_group_id'), 'users', ['group_id'], unique=False)
    op.create_index(op.f('ix_users_active'), 'users', ['is_deleted'], unique=False, postgresql_where='(is_deleted = false)')
    op.drop_column('users', 'date')
    op.drop_column('users', 'user_name')
    op.add_column('groups', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_groups_id'), table_name='groups')
    op.create_index(op.f('ix_groups_active'), 'groups', ['is_deleted'], unique=False, postgresql_where='(is_deleted = false)')
    op.drop_column('groups', 'date')
    op.drop_column('groups', 'group_name')
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_table('reports')
    # ### end Alembic commands ###
